language: go

go:
    - 1.2

install:
    - go get github.com/fabware/skydns/msg
    - go get github.com/fabware/skydns/client
    - go get github.com/fabware/skydock/docker
    - go get github.com/fabware/skydock/utils
    - go get github.com/influxdb/influxdb-go
    - go get github.com/crosbymichael/log
    - go get github.com/robertkrimen/otto
